"""单用途工具配置 - 聚合模块"""

from ._tool_configs_dev import CODE_EXECUTION_TOOLS, GIT_OPERATION_TOOLS, SYSTEM_INFO_TOOLS
from ._tool_configs_file import FILE_OPERATION_TOOLS

# 合并所有工具配置
SINGLE_PURPOSE_TOOLS: dict = {
    **FILE_OPERATION_TOOLS,
    **CODE_EXECUTION_TOOLS,
    **GIT_OPERATION_TOOLS,
    **SYSTEM_INFO_TOOLS,
}

__all__ = [
    "CODE_EXECUTION_TOOLS",
    "FILE_OPERATION_TOOLS",
    "GIT_OPERATION_TOOLS",
    "SINGLE_PURPOSE_TOOLS",
    "SYSTEM_INFO_TOOLS",
]